Added solution and readme back
sleddog/methods-spring-2020 pull request #50
Opened 2020-02-11 23:52 UTC by DanielBachler

Will be redoing the readme in a bit

2020-02-27 21:55 UTC, Jason-Bengtson commented on problems/euler/num22-names-scores/ruby/DanielBachler/solution.rb
> +# Enter your code here. Read input from STDIN. Print output to STDOUT
Maybe elaborate on this comment with what you had in the readme, with things like enter an integer, followed by that many names (was a little confused at first trying to immediately figure out what to do.

2020-02-27 21:56 UTC, Jason-Bengtson commented on problems/euler/num22-names-scores/ruby/DanielBachler/solution.rb
> +end
perhaps have an output showing the task has competed, and the values so there is something to test.

2020-02-27 21:58 UTC, Jason-Bengtson reviewed
The program compiled and ran, no output made it a bit hard to test, and had a bit of trouble initially realizing it wanted me to input something as there was no text prompting me to. Otherwise the code was clean and the logic seems sound, good work!
+1
![command line ruby](https://user-images.githubusercontent.com/51861237/75490741-fc762880-5971-11ea-99a5-3a191e795ce4.png)

2020-02-27 22:30 UTC, Jason-Bengtson requested changes
Just change to have an input prompt, and add an output display to help in testing/knowing program is complete. Thanks!

2020-03-03 05:50 UTC, tyrado commented
+10
I would add like a end solution or maybe a counter for the names so when you put in 4 for the amount of people have that input also go to a loop that takes it in and says like here is person 1: ..... but overall looks great

2020-03-03 06:23 UTC, tyrado commented
![solution](https://user-images.githubusercontent.com/35586877/75748363-80b30d80-5cdc-11ea-9cb0-3e77bbd38393.JPG)
So i was able to give someone a number for a name and I dont think im supposed to be able to do that

2020-03-03 18:52 UTC, Jason-Bengtson approved these changes
runs!
+10

2020-03-03 20:31 UTC, merged